name: Setup the runner

on:
  workflow_dispatch:
  
jobs:
  setup_runner:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      
      - name: disk space - df
        run: df -h
        
      - name: Fetch bbht repo
        continue-on-error: true
        run: |
          echo pwd
          pwd
          echo
          
          echo pwd
          pwd
          echo
          
          chmod +x scripts/install-bash.sh
          ./scripts/install-bash.sh
          
          echo
          echo ls in ~/bbht
          ls -lah
          
          echo
          echo ls in ~
          cd ~
          ls ~ -lah
          
          echo
          echo ls in /root
          cd /root
          ls -lah
          
      - name: disk space - df
        run: df -h
        
      - name: Checking which things are installed without root user
        continue-on-error: true
        run: |
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          echo bash file is not sourced to ~/.bash_profile
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          
          echo
          echo Checking GO
          go version
          echo $GOROOT
 
          echo
          echo Checking nmap
          nmap -h
          
          echo
          echo Checking sublist3r
          sublist3r
          
          echo
          echo Checking assetfinder 
          assetfinder 
          
          echo
          echo Checking waybackurls 
          waybackurls 
          
          echo
          echo Checking subfinder 
          subfinder 
          
          echo
          echo Checking Corsy 
          Corsy 
          
          echo
          echo Checking ruby 
          ruby -version
          ruby --version
          
          echo ~~~~~~~~~~~~~~~~ DONE ~~~~~~~~~~~~~
          
      - name: Checking which things are installed without root user but sourced ~/.bash_profile
        continue-on-error: true
        run: |
          source ~/.bash_profile
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          echo bash file is not sourced to ~/.bash_profile
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          
          echo
          echo Checking GO
          go version
          echo $GOROOT
 
          echo
          echo Checking nmap
          nmap -h
          
          echo
          echo Checking sublist3r
          sublist3r
          
          echo
          echo Checking assetfinder 
          assetfinder 
          
          echo
          echo Checking waybackurls 
          waybackurls 
          
          echo
          echo Checking subfinder 
          subfinder 
          
          echo
          echo Checking Corsy 
          python3 ~/tools/Corsy/corsy.py 
          
          echo
          echo Checking ruby 
          ruby -v
          
          echo
          echo Checking smuggler 
          smuggler 
          
          echo
          echo Checking altdns 
          altdns 
          
          echo
          echo Checking naabu  
          naabu 
          
          echo
          echo Checking httprobe   
          httprobe  
         
          echo ~~~~~~~~~~~~~~~~ DONE ~~~~~~~~~~~~~
          
      

      - name: Checking which things are installed root user but sourced bash_profile
        continue-on-error: true
        run: |
          source ~/.bash_profile
          sudo whoami
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          echo bash file is not sourced to ~/.bash_profile
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          
          echo
          echo Checking GO
          go version
          
          sudo echo
          sudo echo Checking nmap
          sudo nmap -h
          
          sudo echo
          sudo echo Checking sublist3r
          sudo sublist3r
          
          sudo echo
          sudo echo Checking subfinder 
          subfinder 
          
          sudo echo
          sudo echo Checking ruby 
          sudo ruby -v
          
          sudo echo
          sudo echo Checking amass 
          sudo amass

          
          echo ~~~~~~~~~~~~~~~~ DONE ~~~~~~~~~~~~~
