name: Setup the runner

on:
  workflow_dispatch:
  
jobs:
  setup_runner:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      
      - name: disk space - df
        run: df -h
        
      - name: Fetch bbht repo
        run: |
          echo pwd
          pwd
          echo
          
          git clone https://github.com/netanmangal/bbht
          cd bbht
          chmod +x install-bash.sh
          ./install-bash.sh
          
          echo
          echo ls in ~/bbht
          ls
          
      - name: disk space - df
        run: df -h
        
      - name: Checking which things are installed without root user
        continue-on-error: true
        run: |
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          echo bash file is not sourced to ~/.bash_profile
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          
          echo
          echo Checking GO
          go version
          echo $GOROOT
 
          echo
          echo Checking nmap
          nmap -h
          
          echo
          echo Checking sublist3r
          sublist3r
          
          echo
          echo Checking assetfinder 
          assetfinder 
          
          echo
          echo Checking waybackurls 
          waybackurls 
          
          echo
          echo Checking subfinder 
          subfinder 
          
          echo
          echo Checking Corsy 
          Corsy 
          
          echo
          echo Checking ruby 
          ruby -version
          ruby --version
          
          echo ~~~~~~~~~~~~~~~~ DONE ~~~~~~~~~~~~~

      - name: Checking which things are installed without root user but sourced bash_profile
        continue-on-error: true
        run: |
          source ~/.bash_profile
          whoami
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          echo bash file is not sourced to ~/.bash_profile
          echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          
          echo
          echo Checking GO
          go version
          echo $GOROOT
          
          echo
          echo Checking nmap
          nmap -h
          
          echo
          echo Checking sublist3r
          sublist3r
          
          echo
          echo Checking assetfinder 
          assetfinder 
          
          echo
          echo Checking waybackurls 
          waybackurls 
          
          echo
          echo Checking subfinder 
          subfinder 
          
          echo
          echo Checking Corsy 
          Corsy 
          
          echo
          echo Checking ruby 
          ruby -version
          ruby --version
          
          echo ~~~~~~~~~~~~~~~~ DONE ~~~~~~~~~~~~~
